In [1]:
import numpy as np

In [2]:
np.__version__

'1.12.1'

In [3]:
np.show_config()

lapack_opt_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/Anaconda2\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda2\\Library\\include']
blas_opt_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/Anaconda2\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda2\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/Anaconda2\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda2\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/Anaconda2\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', N

In [4]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [6]:
z = np.zeros(10)
z[4] =1 
z

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

In [7]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [8]:
z = np.arange(10,50)
z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [9]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

In [12]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [14]:
np.random.random((3,3,3))

array([[[ 0.54359364,  0.42820963,  0.01844544],
        [ 0.20023498,  0.94409109,  0.41061051],
        [ 0.19476663,  0.7011564 ,  0.93036622]],

       [[ 0.05292438,  0.52223898,  0.54344948],
        [ 0.9726331 ,  0.20181478,  0.05318443],
        [ 0.3110342 ,  0.47067946,  0.33900406]],

       [[ 0.1818115 ,  0.73568809,  0.90503671],
        [ 0.55100751,  0.98642866,  0.95920933],
        [ 0.66333693,  0.19954577,  0.72536324]]])

In [16]:
z = np.random.random((10,10))
print z.min(), z.max()

0.0121895975805 0.98854780158


In [17]:
z = np.random.random(10)
z.mean()

0.53839364643460541

In [21]:
z = np.ones((10,10))
z[1:-1,1:-1] =0
z

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [28]:
print '0 * np.nan  =',0 * np.nan
print 'np.nan == np.nan = ', np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

0 * np.nan  = nan
np.nan == np.nan =  False


False

In [32]:
np.diag(np.arange(1,5), k=-2)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0]])

In [35]:
z = np.zeros((8,8),dtype=int)
z[1::2, ::2] =1 
z[::2, 1::2] =1
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [36]:
np.unravel_index(100, (4,5,6))

(3, 1, 4)

In [37]:
z = np.random.random((5,5))
zmin, zmax = z.min(), z.max()
(z-zmin)/(zmax-zmin)

array([[ 0.90036954,  0.50268142,  0.11265667,  0.15512436,  0.35640779],
       [ 0.35826558,  0.8016438 ,  0.        ,  0.88175622,  0.19207658],
       [ 0.5878659 ,  0.91200078,  0.25768009,  0.35515426,  0.47923772],
       [ 0.64567506,  0.18773538,  0.49024041,  0.3973283 ,  1.        ],
       [ 0.89555072,  0.39365479,  0.54396683,  0.54893271,  0.35052612]])

In [40]:
z = np.arange(10)
z[(z>3)&(z<=8)] *= -1
z

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9])

In [42]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10
